//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblİşlemler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tblİşlemler()
        {
            this.TblCezalar = new HashSet<TblCezalar>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Kitap { get; set; }
        public Nullable<int> Üye { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<System.DateTime> AlışTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<System.DateTime> İadeTarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCezalar> TblCezalar { get; set; }
        public virtual TblKitaplar TblKitaplar { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
        public virtual TblÜyeler TblÜyeler { get; set; }
    }
}
