//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKitaplar()
        {
            this.Tblİşlemler = new HashSet<Tblİşlemler>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public Nullable<int> Kategori { get; set; }
        public Nullable<int> Yazar { get; set; }
        public string BasımYılı { get; set; }
        public string YayınEvi { get; set; }
        public string SayfaSayısı { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Görsel { get; set; }
    
        public virtual TblKategoriler TblKategoriler { get; set; }
        public virtual TblYazar TblYazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tblİşlemler> Tblİşlemler { get; set; }
    }
}
